### PR TITLE
#1 name added to authors

### PR DESCRIPTION
**Pull request by netty-carroll**

### CODE REVIEW

**Review by lisarawlings — APPROVED** [review]

**Review by lisarawlings — APPROVED** [review]

**Review by jennifer-carey — APPROVED** [review]
This looks incredible!

**Review by Lightyyyy — APPROVED** [review]
looks good

**Review by Lightyyyy — APPROVED** [review]
Look great :)

**Review by jennifer-carey — APPROVED** [review]
still amazing

**Review by lisarawlings — APPROVED** [review]
fab

**Review by jennifer-carey — DISMISSED** [review]
I have no idea but why not?

**Review by Lightyyyy — APPROVED** [review]
lovely

**Review by Lightyyyy — DISMISSED** [review]
Very nice indeed

**Review by jennifer-carey — APPROVED** [review]

**Review by ruarplum — APPROVED** [review]

**Review by NickFerra — APPROVED** [review]
smashing

**Pull request merged**
