### PR TITLE
#1 Added name to Authors

### PR DESCRIPTION
**Pull request by lisarawlings**

### CODE REVIEW

**Review by PedroVPSN — APPROVED** [review]
Great job Lisa.

**Review by netty-carroll — APPROVED** [review]
great

**Review by jennifer-carey — APPROVED** [review]
Fabulous

**Review by boothscript — COMMENTED** [review]
great

**Review by boothscript — APPROVED** [review]

**Review by netty-carroll — APPROVED** [review]
great

**Review by PedroVPSN — APPROVED** [review]
looks good

**Review by jennifer-carey — APPROVED** [review]
Done again!

**Pull request merged**
