### PR TITLE
#1 Name added to Authors

### PR DESCRIPTION
**Pull request by NathanRobinson11**

### CODE REVIEW

**Review by jennifer-carey — DISMISSED** [review]
Approved

**Review by ruarplum — APPROVED** [review]
approved

**Review by PedroVPSN — DISMISSED** [review]
Well done.

**Review by jennifer-carey — DISMISSED** [review]

**Review by PedroVPSN — APPROVED** [review]
Good job.

**Review by jennifer-carey — COMMENTED** [review]
Don't you need to remove my name on line 5? I seem to appear twice

**Comment by NathanRobinson11** [comment]
> Don't you need to remove my name on line 5? I seem to appear twice

I have no fixed this, cheers.

**Review by jennifer-carey — APPROVED** [review]
Sweet

**Review by ruarplum — APPROVED** [review]

**Review by PedroVPSN — APPROVED** [review]
Good.

**Pull request merged**
