### PR TITLE
#4 Created HTML file

### PR DESCRIPTION
**Pull request by JoeFoster-cn**
Created index.html with table and iframe

### CODE REVIEW

**Review by Connell97 — APPROVED** [review]
Approved, purely because of RHCP.
Code seems good too!

**Review by JanisMc — CHANGES_REQUESTED** [review]
List favourite songs please

**Review by JanisMc — APPROVED** [review]
Looks good

**Review by Connell97 — APPROVED** [review]
Looks even better than before! Nice work!

**Review by dean418 — APPROVED** [review]

**Pull request merged**
