### PR TITLE
#1 added name

### PR DESCRIPTION
**Pull request by Lightyyyy**

### CODE REVIEW

**Review by netty-carroll — DISMISSED** [review]
great

**Review by jennifer-carey — DISMISSED** [review]
Beautiful!

**Review by ruarplum — APPROVED** [review]
Approved

**Review by ruarplum — APPROVED** [review]
conflict review approved

**Review by ruarplum — APPROVED** [review]
ok

**Review by jennifer-carey — DISMISSED** [review]
Great!

**Review by netty-carroll — DISMISSED** [review]
great

**Review by jadavey91 — COMMENTED** [review]
Looks good

**Review by tamjankowska — DISMISSED** [review]

**Review by ruarplum — APPROVED** [review]

**Review by netty-carroll — DISMISSED** [review]

**Review by jennifer-carey — DISMISSED** [review]

**Review by PedroVPSN — APPROVED** [review]
Approved

**Review by jadavey91 — APPROVED** [review]
I left only a comment before, silly me.

**Review by jennifer-carey — APPROVED** [review]

**Pull request merged**
