### PR TITLE
Evanmorrisdev/5

### PR DESCRIPTION
**Pull request by evanmorrisdev**
Added some style to my HTML file! using style.css

Edited the HTML file to change the title and link to the CSS file.

### CODE REVIEW

**Comment by nmunro** [comment]
Ideally these commits wouldn't have been part of the same branch, it's merging a lot of disconnected work together. Obviously it's just a learning project, but it'd be better to create a branch for a specific ticket and then send it for review, then create a new ticket (even if the original one isn't merged) and start the process again :)

**Review by ap42m — APPROVED** [review]
all clear from me

**Comment by evanmorrisdev** [comment]
@nmunro understood. thanks :)

**Review by Bukky281 — APPROVED** [review]
looks good

**Review by johnmuir2001 — APPROVED** [review]

**Pull request merged**
