### PR TITLE
#2 Added link to GitHub Profile and Pages

### PR DESCRIPTION
**Pull request by NathanRobinson11**

### CODE REVIEW

**Review by lisarawlings — DISMISSED** [review]
fab

**Review by PedroVPSN — APPROVED** [review]
Well done.

**Review by ruarplum — DISMISSED** [review]

**Review by lisarawlings — APPROVED** [review]

**Review by PedroVPSN — APPROVED** [review]
Done.

**Review by lisarawlings — APPROVED** [review]

**Review by ruarplum — APPROVED** [review]

**Review by PedroVPSN — APPROVED** [review]
Good job.

**Pull request merged**
