### PR TITLE
#2 Added links to Readme.md

### PR DESCRIPTION
**Pull request by mafromist**

### CODE REVIEW

**Comment by tamjankowska** [comment]
You have conflicts to resolve here before we can approve it.

**Review by LRWright — APPROVED** [review]
Great :)

**Review by JoeFoster-cn — APPROVED** [review]
🥇

**Review by Riley142 — APPROVED** [review]
All good!

**Review by dean418 — APPROVED** [review]

**Review by JanisMc — APPROVED** [review]

**Pull request merged**
