### PR TITLE
#2 Add links to GitHub profile and pages

### PR DESCRIPTION
**Pull request by jennifer-carey**

### CODE REVIEW

**Review by ruarplum — APPROVED** [review]
yes

**Review by NickFerra — APPROVED** [review]
great

**Review by nmunro — APPROVED** [review]
Looks good

**Review by NickFerra — DISMISSED** [review]
yep

**Review by ruarplum — DISMISSED** [review]
yes

**Review by lisarawlings — APPROVED** [review]
fab

**Review by NickFerra — APPROVED** [review]

**Review by ruarplum — APPROVED** [review]

**Review by lisarawlings — APPROVED** [review]
great

**Pull request merged**
