### PR TITLE
#1 add name

### PR DESCRIPTION
**Pull request by phiddle**

### CODE REVIEW

**Comment by phiddle** [comment]
I added MD links

**Review by JakeyD11 — APPROVED** [review]
Looks good to me

**Review by tamjankowska — APPROVED** [review]

**Review by jadavey91 — COMMENTED** [review]
I need to leave a comment apparently

**Review by andreigoncearenco — APPROVED** [review]

**Review by jadavey91 — APPROVED** [review]
Duh

**Pull request merged**
