### PR TITLE
#2 Added  links to github profiles & github pages

### PR DESCRIPTION
**Pull request by Riley142**

### CODE REVIEW

**Review by carys23 — APPROVED** [review]
looks good

**Review by JoeFoster-cn — APPROVED** [review]

**Review by JanisMc — CHANGES_REQUESTED** [review]
please resolve merge conflicts

**Review by Riley142 — COMMENTED** [review]
fixed merge conflict

**Review by Riley142 — COMMENTED** [review]
fixed merge conflict

**Review by dean418 — APPROVED** [review]

**Review by evanmorrisdev — APPROVED** [review]

**Review by LRWright — APPROVED** [review]

**Review by JanisMc — APPROVED** [review]

**Pull request merged**
