### PR TITLE
Everything up to ticket 7

### PR DESCRIPTION
**Pull request by JakeyD11**
this is still all in 1 branch because im an idiot

### CODE REVIEW

**Review by lisarawlings — APPROVED** [review]

**Comment by johnfenlon** [comment]
approved

**Review by Lightyyyy — APPROVED** [review]
Good stuff!

**Review by ruarplum — APPROVED** [review]

**Review by JanisMc — DISMISSED** [review]
please resolve merge conflicts

**Review by evanmorrisdev — DISMISSED** [review]

**Review by evanmorrisdev — DISMISSED** [review]

**Review by Lightyyyy — DISMISSED** [review]

**Review by evanmorrisdev — APPROVED** [review]

**Review by Lightyyyy — APPROVED** [review]
Lookin good :)

**Review by jadavey91 — APPROVED** [review]
Lets go!

**Pull request merged**
