### PR TITLE
1 Add your name to the authors file

### PR DESCRIPTION
**Pull request by nisharai26**

### CODE REVIEW

**Review by lisarawlings — DISMISSED** [review]
Great

**Comment by boothscript** [comment]
this is a test

**Comment by boothscript** [comment]
please resolve conflicts before I review Nisha

**Review by ggemcila — APPROVED** [review]

**Review by Edwine-R — APPROVED** [review]

**Review by ggemcila — APPROVED** [review]
This seems good to me

**Review by nmunro — APPROVED** [review]

**Pull request merged**
