### PR TITLE
#4 Added HTML file

### PR DESCRIPTION
**Pull request by mafromist**

### CODE REVIEW

**Review by JoeFoster-cn — DISMISSED** [review]
Looks good!

**Review by JoeFoster-cn — APPROVED** [review]

**Review by carys23 — APPROVED** [review]

**Review by JanisMc — CHANGES_REQUESTED** [review]
please resolve merge conflicts. #1 & #4 both seem to be on this branch does that need to be fixed?

**Review by JoeFoster-cn — APPROVED** [review]
Looks good to me 👍

**Comment by mafromist** [comment]
> please resolve merge conflicts. #1 & #4 both seem to be on this branch does that need to be fixed?

I have solved the conflicts thanks 👍

**Review by JanisMc — APPROVED** [review]

**Review by Riley142 — APPROVED** [review]

**Review by LRWright — APPROVED** [review]

**Pull request merged**
