### PR TITLE
#4 index.html / table / iframe

### PR DESCRIPTION
**Pull request by ap42m**
Added the idex.html file with a table of songs and embeded video

### CODE REVIEW

**Review by nmunro — APPROVED** [review]
Nice and concise super easy to review 👍

**Review by evanmorrisdev — APPROVED** [review]

**Comment by SteIddon** [comment]
Looks good

**Review by SteIddon — COMMENTED** [review]
Looks good

**Review by Bukky281 — APPROVED** [review]
looks good

**Pull request merged**
