### PR TITLE
#1 add name to authors

### PR DESCRIPTION
**Pull request by NickFerra**

### CODE REVIEW

**Review by jennifer-carey — APPROVED** [review]
Super

**Review by netty-carroll — DISMISSED** [review]
great

**Review by PedroVPSN — APPROVED** [review]
Great.

**Review by ruarplum — APPROVED** [review]
yup

**Review by PedroVPSN — APPROVED** [review]
Well done.

**Review by PedroVPSN — APPROVED** [review]
Well done.

**Review by jennifer-carey — APPROVED** [review]
Cool

**Pull request merged**
