### PR TITLE
2 Add a link to your github profile & github pages url to the README.md file

### PR DESCRIPTION
**Pull request by LRWright**

### CODE REVIEW

**Review by mafromist — DISMISSED** [review]
Looks good

**Review by JoeFoster-cn — APPROVED** [review]
👍

**Comment by LRWright** [comment]
Resolved conflicts

**Review by Riley142 — APPROVED** [review]
all good

**Review by dean418 — APPROVED** [review]

**Review by JanisMc — APPROVED** [review]

**Pull request merged**
